webtalk_init -webtalk_dir D:/Users/sasaken/3a/cpuex/cpuex2020_core/test/test_alu/test_alu.sim/sim_1/behav/xsim/xsim.dir/test_alu_v_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Nov 28 17:29:15 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211142045_1777515821_210725329_520" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a1e8e2e2-cfa9-4a81-a21a-3adb2f58cb11" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "072f4d879cd84feca863306e710c26f8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6592_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4283725019 -regid "211142045_1777515821_210725329_520" -xml D:/Users/sasaken/3a/cpuex/cpuex2020_core/test/test_alu/test_alu.sim/sim_1/behav/xsim/xsim.dir/test_alu_v_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Users/sasaken/3a/cpuex/cpuex2020_core/test/test_alu/test_alu.sim/sim_1/behav/xsim/xsim.dir/test_alu_v_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Users/sasaken/3a/cpuex/cpuex2020_core/test/test_alu/test_alu.sim/sim_1/behav/xsim/xsim.dir/test_alu_v_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
